version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres_jwt
    environment:
    POSTGRES_DB: "postgres_test"
    POSTGRES_USER: "user"
    POSTGRES_PASSWORD: "password"
    ports:
      - "3000:5432"
    volumes:
      - db_postgres:/var/lib/postgresql/data

volumes:
  db_postgres:
